# Generated by Django 5.2.1 on 2025-05-20 18:04

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Asosiy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Boshqaruv paneli',
                'verbose_name_plural': 'Boshqaruv panellari',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('widget_type', models.CharField(choices=[('sales_summary', 'Sotuvlar umumiy'), ('top_products', 'Top mahsulotlar'), ('inventory_status', 'Inventarizatsiya holati'), ('recent_orders', "So'nggi buyurtmalar"), ('category_distribution', 'Kategoriyalar taqsimoti'), ('sales_trend', 'Sotuvlar tendensiyasi'), ('customer_stats', 'Mijozlar statistikasi')], max_length=50, verbose_name='Widget turi')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Pozitsiya')),
                ('col_span', models.PositiveSmallIntegerField(default=1, verbose_name="Ustun o'lchami")),
                ('row_span', models.PositiveSmallIntegerField(default=1, verbose_name="Qator o'lchami")),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Sozlamalar')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.dashboard', verbose_name='Boshqaruv paneli')),
            ],
            options={
                'verbose_name': 'Dashboard widget',
                'verbose_name_plural': 'Dashboard widgetlar',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDashboard',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Asosiy')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'historical Boshqaruv paneli',
                'verbose_name_plural': 'historical Boshqaruv panellari',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDashboardWidget',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name="O'zgartirilgan sana")),
                ('widget_type', models.CharField(choices=[('sales_summary', 'Sotuvlar umumiy'), ('top_products', 'Top mahsulotlar'), ('inventory_status', 'Inventarizatsiya holati'), ('recent_orders', "So'nggi buyurtmalar"), ('category_distribution', 'Kategoriyalar taqsimoti'), ('sales_trend', 'Sotuvlar tendensiyasi'), ('customer_stats', 'Mijozlar statistikasi')], max_length=50, verbose_name='Widget turi')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Pozitsiya')),
                ('col_span', models.PositiveSmallIntegerField(default=1, verbose_name="Ustun o'lchami")),
                ('row_span', models.PositiveSmallIntegerField(default=1, verbose_name="Qator o'lchami")),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Sozlamalar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dashboard', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.dashboard', verbose_name='Boshqaruv paneli')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dashboard widget',
                'verbose_name_plural': 'historical Dashboard widgetlar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
