# Generated by Django 5.2.1 on 2025-05-20 18:04

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=200, verbose_name='Nomi/Firma')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Kontakt shaxs')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Shahar')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Davlat')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Soliq identifikatori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=200, verbose_name='Nomi/Firma')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Kontakt shaxs')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Shahar')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Davlat')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Soliq identifikatori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Mijoz',
                'verbose_name_plural': 'historical Mijozlar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name="O'zgartirilgan sana")),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Buyurtma raqami')),
                ('order_date', models.DateField(verbose_name='Buyurtma sanasi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('confirmed', 'Tasdiqlangan'), ('processing', 'Jarayonda'), ('ready', 'Tayyor'), ('shipped', "Jo'natilgan"), ('delivered', 'Yetkazilgan'), ('cancelled', 'Bekor qilingan'), ('returned', 'Qaytarilgan')], default='draft', max_length=20, verbose_name='Holati')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Yetkazish manzili')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Taxminiy yetkazish sanasi')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami summa')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Chegirma')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Soliq')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Yetkazib berish narxi')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Yakuniy summa')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.customer', verbose_name='Mijoz')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'historical Buyurtma',
                'verbose_name_plural': 'historical Buyurtmalar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Buyurtma raqami')),
                ('order_date', models.DateField(verbose_name='Buyurtma sanasi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('confirmed', 'Tasdiqlangan'), ('processing', 'Jarayonda'), ('ready', 'Tayyor'), ('shipped', "Jo'natilgan"), ('delivered', 'Yetkazilgan'), ('cancelled', 'Bekor qilingan'), ('returned', 'Qaytarilgan')], default='draft', max_length=20, verbose_name='Holati')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Yetkazish manzili')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Taxminiy yetkazish sanasi')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami summa')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Chegirma')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Soliq')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Yetkazib berish narxi')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Yakuniy summa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.customer', verbose_name='Mijoz')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-order_date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrderItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name="O'zgartirilgan sana")),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birlik narxi')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chegirma (%)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Umumiy narx')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.productvariant', verbose_name='Mahsulot varianti')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'historical Buyurtma elementi',
                'verbose_name_plural': 'historical Buyurtma elementlari',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birlik narxi')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chegirma (%)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Umumiy narx')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='Buyurtma')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.productvariant', verbose_name='Mahsulot varianti')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
    ]
