# Generated by Django 5.2.1 on 2025-05-20 18:04

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='Belgi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Asosiy')),
            ],
            options={
                'verbose_name': 'Valyuta',
                'verbose_name_plural': 'Valyutalar',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCurrency',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name="O'zgartirilgan sana")),
                ('code', models.CharField(db_index=True, max_length=3, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='Belgi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Asosiy')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Valyuta',
                'verbose_name_plural': 'historical Valyutalar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
