# Generated by Django 5.2.1 on 2025-05-20 18:04

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=200, verbose_name='Kompaniya nomi')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Yuridik nomi')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Soliq identifikatori')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name="Ro'yxatdan o'tish raqami")),
                ('address', models.TextField(verbose_name='Manzil')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Pochta indeksi')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Favicon')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank nomi')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Bank hisobi')),
                ('bank_code', models.CharField(blank=True, max_length=50, verbose_name='Bank kodi')),
            ],
            options={
                'verbose_name': "Kompaniya ma'lumotlari",
                'verbose_name_plural': "Kompaniya ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Kalit')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('value_type', models.CharField(choices=[('text', 'Matn'), ('number', 'Raqam'), ('boolean', 'Mantiqiy'), ('date', 'Sana'), ('json', 'JSON')], max_length=20, verbose_name='Qiymat turi')),
                ('value_text', models.TextField(blank=True, verbose_name='Matn qiymati')),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Raqam qiymati')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Mantiqiy qiymati')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Sana qiymati')),
                ('value_json', models.JSONField(blank=True, null=True, verbose_name='JSON qiymati')),
                ('is_public', models.BooleanField(default=False, help_text="Agar belgilansa, bu sozlama autentifikatsiyasiz foydalanuvchilarga ko'rinadi", verbose_name='Ommaviy')),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCompanyInfo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=200, verbose_name='Kompaniya nomi')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Yuridik nomi')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Soliq identifikatori')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name="Ro'yxatdan o'tish raqami")),
                ('address', models.TextField(verbose_name='Manzil')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Pochta indeksi')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('logo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Logo')),
                ('favicon', models.TextField(blank=True, max_length=100, null=True, verbose_name='Favicon')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank nomi')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Bank hisobi')),
                ('bank_code', models.CharField(blank=True, max_length=50, verbose_name='Bank kodi')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical Kompaniya ma'lumotlari",
                'verbose_name_plural': "historical Kompaniya ma'lumotlari",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSystemSetting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name="O'zgartirilgan sana")),
                ('key', models.CharField(db_index=True, max_length=100, verbose_name='Kalit')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('value_type', models.CharField(choices=[('text', 'Matn'), ('number', 'Raqam'), ('boolean', 'Mantiqiy'), ('date', 'Sana'), ('json', 'JSON')], max_length=20, verbose_name='Qiymat turi')),
                ('value_text', models.TextField(blank=True, verbose_name='Matn qiymati')),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Raqam qiymati')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Mantiqiy qiymati')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Sana qiymati')),
                ('value_json', models.JSONField(blank=True, null=True, verbose_name='JSON qiymati')),
                ('is_public', models.BooleanField(default=False, help_text="Agar belgilansa, bu sozlama autentifikatsiyasiz foydalanuvchilarga ko'rinadi", verbose_name='Ommaviy')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tizim sozlamasi',
                'verbose_name_plural': 'historical Tizim sozlamalari',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
